Admin={
	[4]={
		Name="Project Lead",RGB={255,170,100},HEX="#ffac69",
		Permissions={
			DevFunctions=true,TeleportTroughF11=true,Vanish=true,GiveCar=true,Spectate=true,
		},
	},
	[3]={
		Name="Administrator",RGB={255,120,120},HEX="#ff7676",
		Permissions={
			DevFunctions=false,TeleportTroughF11=true,Vanish=true,GiveCar=false,Spectate=true,
		},
	},
	[2]={
		Name="Moderator",RGB={80,255,170},HEX="#50FFAA",
		Permissions={
			DevFunctions=false,TeleportTroughF11=false,Vanish=true,GiveCar=false,Spectate=true,
		},
	},
	[1]={
		Name="Supporter",RGB={240,255,120},HEX="#F0FF78",
		Permissions={
			DevFunctions=false,TeleportTroughF11=false,Vanish=false,GiveCar=false,Spectate=true,
		},
	},
	[0]={
		Name="Player",RGB={255,255,255},HEX="#ffffff",
		Permissions={
			DevFunctions=false,TeleportTroughF11=false,Vanish=false,GiveCar=false,Spectate=false,
		},
	},
}