Traders={
    ["Regular"]={
        Blip={2621.2,-1081.9,69.6,6,255,255,255, "Market"},--x,y,z,icon,r,g,b, tooltip
        Ped={33,2621.2,-1081.9,69.6,175, 2.6, "General Stuff"},--ID,x,y,z,rotZ, distance, pedTitle
        Items={
            {
                Item="Bitcoin",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=2,
                OnlyInCrates=false,
            },
            {
                Item="Medikit",
                Buyable=true,
                Sellable=false,
                PreviewObject=nil,
                Level=2,
                OnlyInCrates=false,
            },
            {
                Item="Dynamite",
                Buyable=true,
                Sellable=false,
                PreviewObject=nil,
                Level=2,
                OnlyInCrates=false,
            },
            {
                Item="Cannabis",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="CrowbarExtended",
                Buyable=true,
                Sellable=false,
                PreviewObject=nil,
                Level=2,
                OnlyInCrates=false,
            },
            {
                Item="Crowbar",
                Buyable=true,
                Sellable=false,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Pickaxe",
                Buyable=true,
                Sellable=false,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
        },
    },
    ["Farm"]={
        Blip={-1432.7,-1538.8,101.7,6,60,255,60, "Market"},--x,y,z,icon,r,g,b, tooltip
        Ped={201,-1432.7,-1538.8,101.7,90, 1.2, "Farming stuff"},--ID,x,y,z,rotZ, distance, pedTitle
        Items={
            {
                Item="Bitcoin",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=2,
                OnlyInCrates=false,
            },
            {
                Item="Pear",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Apple",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Orange",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Coconut",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Emerald",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=4,
                OnlyInCrates=false,
            },
            {
                Item="Ruby",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=3,
                OnlyInCrates=false,
            },
            {
                Item="Diamond",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=3,
                OnlyInCrates=false,
            },
            {
                Item="GoldIngot",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=2,
                OnlyInCrates=false,
            },
            {
                Item="IronIngot",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=2,
                OnlyInCrates=false,
            },
            {
                Item="Cannabis",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Coal",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Stone",
                Buyable=false,
                Sellable=true,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
        },
    },
    ["Wheels"]={
        Ped={50,2620.7,-1091.9,69.6,0, 2.6, "Vehicle stuff"},--ID,x,y,z,rotZ, distance, pedTitle
        Items={
            {
                Item="Nitro",
                Buyable=true,
                Sellable=false,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Repairkit",
                Buyable=true,
                Sellable=false,
                PreviewObject=nil,
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Wheel_1877",
                Buyable=true,
                Sellable=false,
                PreviewObject={1877,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Wheel_1878",
                Buyable=true,
                Sellable=false,
                PreviewObject={1878,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Wheel_1879",
                Buyable=false,
                Sellable=false,
                PreviewObject={1879,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Wheel_1880",
                Buyable=true,
                Sellable=false,
                PreviewObject={1880,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Wheel_1881",
                Buyable=true,
                Sellable=false,
                PreviewObject={1881,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Wheel_1882",
                Buyable=false,
                Sellable=false,
                PreviewObject={1882,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Wheel_1901",
                Buyable=false,
                Sellable=false,
                PreviewObject={1901,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Wheel_1902",
                Buyable=true,
                Sellable=false,
                PreviewObject={1902,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Wheel_1903",
                Buyable=false,
                Sellable=false,
                PreviewObject={1903,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Wheel_1904",
                Buyable=false,
                Sellable=false,
                PreviewObject={1904,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Wheel_1911",
                Buyable=false,
                Sellable=false,
                PreviewObject={1911,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Wheel_1921",
                Buyable=true,
                Sellable=false,
                PreviewObject={1921,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Wheel_1930",
                Buyable=true,
                Sellable=false,
                PreviewObject={1930,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Wheel_1931",
                Buyable=false,
                Sellable=false,
                PreviewObject={1931,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Wheel_1932",
                Buyable=false,
                Sellable=false,
                PreviewObject={1932,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Wheel_1933",
                Buyable=false,
                Sellable=false,
                PreviewObject={1933,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Wheel_1940",
                Buyable=true,
                Sellable=false,
                PreviewObject={1940,nil,nil,true},--objectID
                Level=1,
                OnlyInCrates=false,
            },
        },
    },
    ["WeaponSkins"]={
        Ped={113,2613.7,-1081.4,69.6,175, 2.6, "Weapon skins"},--ID,x,y,z,rotZ, distance, pedTitle
        Items={
            --Deagle
            {
                Item="Weapon_24_1",
                Buyable=true,
                Sellable=false,
                PreviewObject={348,24,1,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_24_2",
                Buyable=true,
                Sellable=false,
                PreviewObject={348,24,2,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_24_3",
                Buyable=true,
                Sellable=false,
                PreviewObject={348,24,3,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_24_4",
                Buyable=false,
                Sellable=false,
                PreviewObject={348,24,4,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_24_5",
                Buyable=true,
                Sellable=false,
                PreviewObject={348,24,5,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_24_6",
                Buyable=false,
                Sellable=false,
                PreviewObject={348,24,6,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_24_7",
                Buyable=false,
                Sellable=false,
                PreviewObject={348,24,7,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_24_8",
                Buyable=false,
                Sellable=false,
                PreviewObject={348,24,8,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },

            --Shotgun
            {
                Item="Weapon_25_1",
                Buyable=true,
                Sellable=false,
                PreviewObject={349,25,1,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_25_2",
                Buyable=false,
                Sellable=false,
                PreviewObject={349,25,2,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_25_3",
                Buyable=false,
                Sellable=false,
                PreviewObject={349,25,3,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_25_4",
                Buyable=true,
                Sellable=false,
                PreviewObject={349,25,4,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_25_5",
                Buyable=false,
                Sellable=false,
                PreviewObject={349,25,5,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_25_6",
                Buyable=true,
                Sellable=false,
                PreviewObject={349,25,6,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_25_7",
                Buyable=true,
                Sellable=false,
                PreviewObject={349,25,7,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_25_8",
                Buyable=true,
                Sellable=false,
                PreviewObject={349,25,8,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_25_9",
                Buyable=true,
                Sellable=false,
                PreviewObject={349,25,9,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_25_10",
                Buyable=true,
                Sellable=false,
                PreviewObject={349,25,10,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_25_11",
                Buyable=true,
                Sellable=false,
                PreviewObject={349,25,11,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_25_12",
                Buyable=false,
                Sellable=false,
                PreviewObject={349,25,12,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_25_13",
                Buyable=true,
                Sellable=false,
                PreviewObject={349,25,13,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_25_14",
                Buyable=true,
                Sellable=false,
                PreviewObject={349,25,14,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_25_15",
                Buyable=false,
                Sellable=false,
                PreviewObject={349,25,15,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_25_16",
                Buyable=false,
                Sellable=false,
                PreviewObject={349,25,16,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_25_17",
                Buyable=false,
                Sellable=false,
                PreviewObject={349,25,17,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_25_18",
                Buyable=true,
                Sellable=false,
                PreviewObject={349,25,18,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },

            --AK
            {
                Item="Weapon_30_1",
                Limited=1730458800,
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,1,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_30_2",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,2,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            --[[ {
                Item="Weapon_30_3",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,3,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            {
                Item="Weapon_30_4",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,4,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_30_5",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,5,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_30_6",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,6,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_30_7",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,7,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            --[[ {
                Item="Weapon_30_8",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,8,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            --[[ {
                Item="Weapon_30_9",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,9,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            {
                Item="Weapon_30_10",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,10,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            --[[ {
                Item="Weapon_30_11",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,11,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            --[[ {
                Item="Weapon_30_12",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,12,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            --[[ {
                Item="Weapon_30_13",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,13,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            --[[ {
                Item="Weapon_30_14",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,14,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            {
                Item="Weapon_30_15",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,15,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            --[[ {
                Item="Weapon_30_16",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,16,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            --[[ {
                Item="Weapon_30_17",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,17,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            {
                Item="Weapon_30_18",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,18,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            --[[ {
                Item="Weapon_30_19",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,19,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            --[[ {
                Item="Weapon_30_20",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,20,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            {
                Item="Weapon_30_21",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,21,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_30_22",
                Buyable=true,
                Sellable=false,
                PreviewObject={355,30,22,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_30_23",
                Buyable=false,
                Sellable=false,
                PreviewObject={355,30,23,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_30_24",
                Buyable=false,
                Sellable=false,
                PreviewObject={355,30,24,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_30_25",
                Buyable=false,
                Sellable=false,
                PreviewObject={355,30,25,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_30_26",
                Buyable=false,
                Sellable=false,
                PreviewObject={355,30,26,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },

            --M4
            {
                Item="Weapon_31_1",
                Limited=1730458800,
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,1,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_31_2",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,2,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_31_3",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,3,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_31_4",
                Buyable=false,
                Sellable=false,
                PreviewObject={356,31,4,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_31_5",
                Buyable=false,
                Sellable=false,
                PreviewObject={356,31,5,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_31_6",
                Buyable=false,
                Sellable=false,
                PreviewObject={356,31,6,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_31_7",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,7,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
           --[[  {
                Item="Weapon_31_8",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,8,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            {
                Item="Weapon_31_9",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,9,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_31_10",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,10,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            --[[ {
                Item="Weapon_31_11",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,11,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            --[[ {
                Item="Weapon_31_12",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,12,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            --[[ {
                Item="Weapon_31_13",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,13,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            {
                Item="Weapon_31_14",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,14,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            --[[ {
                Item="Weapon_31_15",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,15,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            {
                Item="Weapon_31_16",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,16,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_31_17",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,17,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_31_18",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,18,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            --[[ {
                Item="Weapon_31_19",
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,19,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            --[[ {
                Item="Weapon_31_20",
                Limited=1722333600,
                Buyable=true,
                Sellable=false,
                PreviewObject={356,31,20,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            
            --Sniper
            --[[ {
                Item="Weapon_34_1",
                Buyable=true,
                Sellable=false,
                PreviewObject={358,34,1,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_34_2",
                Buyable=true,
                Sellable=false,
                PreviewObject={358,34,2,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            }, ]]
            {
                Item="Weapon_34_3",
                Buyable=true,
                Sellable=false,
                PreviewObject={358,34,3,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_34_4",
                Buyable=false,
                Sellable=false,
                PreviewObject={358,34,4,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_34_5",
                Buyable=true,
                Sellable=false,
                PreviewObject={358,34,5,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_34_6",
                Buyable=false,
                Sellable=false,
                PreviewObject={358,34,6,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_34_7",
                Buyable=true,
                Sellable=false,
                PreviewObject={358,34,7,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_34_8",
                Buyable=true,
                Sellable=false,
                PreviewObject={358,34,8,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_34_9",
                Buyable=true,
                Sellable=false,
                PreviewObject={358,34,9,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_34_10",
                Buyable=true,
                Sellable=false,
                PreviewObject={358,34,10,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_34_11",
                Buyable=true,
                Sellable=false,
                PreviewObject={358,34,11,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=false,
            },
            {
                Item="Weapon_34_12",
                Buyable=false,
                Sellable=false,
                PreviewObject={358,34,12,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_34_13",
                Buyable=false,
                Sellable=false,
                PreviewObject={358,34,13,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_34_14",
                Buyable=false,
                Sellable=false,
                PreviewObject={358,34,14,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_34_15",
                Buyable=false,
                Sellable=false,
                PreviewObject={358,34,15,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_34_16",
                Buyable=false,
                Sellable=false,
                PreviewObject={358,34,16,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
            {
                Item="Weapon_34_17",
                Buyable=false,
                Sellable=false,
                PreviewObject={358,34,17,false},--objectID,weaponID,skinID,rotFix
                Level=1,
                OnlyInCrates=true,
            },
        },
    },
};

TraderSettings={
    Progress={
        GiveExp={
            ["Regular"]={
                [1]=1,
                [2]=1,
                [3]=0,
            },
            ["Farm"]={
                [1]=1,
                [2]=1,
                [3]=1,
                [4]=0,
            },
            ["Wheels"]={
                [1]=1,
                [2]=0,
            },
            ["WeaponSkins"]={
                [1]=0,
            },
        },
        LevelExp={
            ["Regular"]={
                [1]=300,
                [2]=600,
                [3]=9999999999,
            },
            ["Farm"]={
                [1]=500,
                [2]=1000,
                [3]=2000,
                [4]=9999999999,
            },
            ["Wheels"]={
                [1]=300,
                [2]=9999999999,
            },
            ["WeaponSkins"]={
                [1]=9999999999,
            },
        },
    },
    Prices={
        ["Bitcoin"]={15000,25000},
        ["Emerald"]={5000,7500},
        ["Ruby"]={2000,3500},
        ["Diamond"]={1000,1500},
        ["IronIngot"]={100,150},
        ["GoldIngot"]={200,300},
        ["Coal"]={15,22},
        ["Stone"]={10,15},
        ["Orange"]={80,100},
        ["Apple"]={80,100},
        ["Pear"]={80,100},
        ["Coconut"]={85,105},
        ["Crowbar"]={800,1000},
        ["CrowbarExtended"]={5000,6500},
        ["Dynamite"]={5000,6500},
        ["Pickaxe"]={500,650},
        ["Medikit"]={800,1000},
        ["Cannabis"]={200,225},

        ["Nitro"]={15,25},
        ["Repairkit"]={2000,4000},
        ["Wheel_1877"]={500000,500000},
        ["Wheel_1878"]={500000,500000},
        ["Wheel_1879"]={3000000,3000000},
        ["Wheel_1880"]={500000,500000},
        ["Wheel_1881"]={500000,500000},
        ["Wheel_1882"]={3000000,3000000},
        ["Wheel_1901"]={3000000,3000000},
        ["Wheel_1902"]={500000,500000},
        ["Wheel_1903"]={3000000,3000000},
        ["Wheel_1904"]={3000000,3000000},
        ["Wheel_1911"]={3000000,3000000},
        ["Wheel_1921"]={500000,500000},
        ["Wheel_1930"]={500000,500000},
        ["Wheel_1931"]={3000000,3000000},
        ["Wheel_1932"]={3000000,3000000},
        ["Wheel_1933"]={3000000,3000000},
        ["Wheel_1940"]={1500000,1500000},

        ["Weapon_24_1"]={1500000,1500000},
        ["Weapon_24_2"]={1500000,1500000},
        ["Weapon_24_3"]={1500000,1500000},
        ["Weapon_24_4"]={3000000,3000000},--Limited
        ["Weapon_24_5"]={1500000,1500000},
        ["Weapon_24_6"]={3000000,3000000},--Limited
        ["Weapon_24_7"]={3000000,3000000},--Limited
        ["Weapon_24_8"]={3000000,3000000},--Limited

        ["Weapon_25_1"]={1500000,1500000},
        ["Weapon_25_2"]={1500000,1500000},
        ["Weapon_25_3"]={1500000,1500000},
        ["Weapon_25_4"]={1500000,1500000},
        ["Weapon_25_5"]={1500000,1500000},
        ["Weapon_25_6"]={1500000,1500000},
        ["Weapon_25_7"]={1500000,1500000},
        ["Weapon_25_8"]={1500000,1500000},
        ["Weapon_25_9"]={1500000,1500000},
        ["Weapon_25_10"]={1500000,1500000},
        ["Weapon_25_11"]={1500000,1500000},
        ["Weapon_25_12"]={1500000,1500000},
        ["Weapon_25_13"]={1500000,1500000},
        ["Weapon_25_14"]={1500000,1500000},
        ["Weapon_25_15"]={1500000,1500000},
        ["Weapon_25_16"]={1500000,1500000},
        ["Weapon_25_17"]={1500000,1500000},
        ["Weapon_25_18"]={1500000,1500000},

        ["Weapon_30_1"]={3000000,3000000},--Limited
        ["Weapon_30_2"]={1500000,1500000},
        ["Weapon_30_3"]={3000000,3000000},--Limited
        ["Weapon_30_4"]={1500000,1500000},
        ["Weapon_30_5"]={1500000,1500000},
        ["Weapon_30_6"]={1500000,1500000},
        ["Weapon_30_7"]={1500000,1500000},
        ["Weapon_30_8"]={3000000,3000000},--Limited
        ["Weapon_30_9"]={3000000,3000000},--Limited
        ["Weapon_30_10"]={1500000,1500000},
        ["Weapon_30_11"]={3000000,3000000},--Limited
        ["Weapon_30_12"]={3000000,3000000},--Limited
        ["Weapon_30_13"]={3000000,3000000},--Limited
        ["Weapon_30_14"]={3000000,3000000},--Limited
        ["Weapon_30_15"]={1500000,1500000},
        ["Weapon_30_16"]={3000000,3000000},--Limited
        ["Weapon_30_17"]={3000000,3000000},--Limited
        ["Weapon_30_18"]={1500000,1500000},
        ["Weapon_30_19"]={3000000,3000000},--Limited
        ["Weapon_30_20"]={3000000,3000000},--Limited
        ["Weapon_30_21"]={1500000,1500000},
        ["Weapon_30_22"]={1500000,1500000},
        ["Weapon_30_23"]={3000000,3000000},--Limited
        ["Weapon_30_24"]={3000000,3000000},--Limited
        ["Weapon_30_25"]={3000000,3000000},--Limited
        ["Weapon_30_26"]={3000000,3000000},--Limited

        ["Weapon_31_1"]={3000000,3000000},--Limited
        ["Weapon_31_2"]={1500000,1500000},
        ["Weapon_31_3"]={1500000,1500000},
        ["Weapon_31_4"]={3000000,3000000},--Limited
        ["Weapon_31_5"]={3000000,3000000},--Limited
        ["Weapon_31_6"]={3000000,3000000},--Limited
        ["Weapon_31_7"]={1500000,1500000},
        ["Weapon_31_8"]={3000000,3000000},--Limited
        ["Weapon_31_9"]={1500000,1500000},
        ["Weapon_31_10"]={1500000,1500000},
        ["Weapon_31_11"]={3000000,3000000},--Limited
        ["Weapon_31_12"]={3000000,3000000},--Limited
        ["Weapon_31_13"]={3000000,3000000},--Limited
        ["Weapon_31_14"]={1500000,1500000},
        ["Weapon_31_15"]={3000000,3000000},--Limited
        ["Weapon_31_16"]={1500000,1500000},
        ["Weapon_31_17"]={1500000,1500000},
        ["Weapon_31_18"]={1500000,1500000},
        ["Weapon_31_19"]={3000000,3000000},--Limited
        ["Weapon_31_20"]={3000000,3000000},--Limited

        ["Weapon_34_1"]={3000000,3000000},--Limited
        ["Weapon_34_2"]={3000000,3000000},--Limited
        ["Weapon_34_3"]={1500000,1500000},
        ["Weapon_34_4"]={3000000,3000000},--Limited
        ["Weapon_34_5"]={1500000,1500000},
        ["Weapon_34_6"]={3000000,3000000},--Limited
        ["Weapon_34_7"]={1500000,1500000},
        ["Weapon_34_8"]={1500000,1500000},
        ["Weapon_34_9"]={1500000,1500000},
        ["Weapon_34_10"]={1500000,1500000},
        ["Weapon_34_11"]={1500000,1500000},
        ["Weapon_34_12"]={3000000,3000000},--Limited
        ["Weapon_34_13"]={3000000,3000000},--Limited
        ["Weapon_34_14"]={3000000,3000000},--Limited
        ["Weapon_34_15"]={3000000,3000000},--Limited
        ["Weapon_34_16"]={3000000,3000000},--Limited
        ["Weapon_34_17"]={3000000,3000000},--Limited
    },
}