Userpanel={
    Categories={
        {icon="fas fa-user",id="Character",},
        {icon="fas fa-turn-up",id="Levels",},
        {icon="fas fa-trophy",id="Achievements",},
        {icon="fas fa-cog",id="Settings",},
        {icon="fas fa-star",id="Premium",},
    },
    SubCategories={
        ["Settings"]={
            {icon="fal fa-language",id="Language",},
            {icon="fas fa-bell",id="Hitbell",},
            {icon="fas fa-xmark",id="Hitmarker",},
            {icon="fas fa-crosshairs",id="CrosshairNormal",},
            {icon="fas fa-crosshairs",id="CrosshairSniper",},
            {icon="fab fa-windows",id="WindowsNotifications",},
            {icon="fas fa-cloud-snow",id="Effects",},
            {icon="far fa-spray-can",id="Shaders",},
        },
        ["Premium"]={
            {icon="fas fa-treasure-chest",id="Crates",},
        },
    },

    Settings={
        ["Language"]={
            {icon="fal fa-language",value=0,name="English",},
            {icon="fal fa-language",value=1,name="German",},
            {icon="fal fa-language",value=2,name="Polski",},
            {icon="fal fa-language",value=3,name="Brazil",},
        },
        ["Hitbell"]={
            {icon="fas fa-volume-xmark",value=0,name="Disable",},
            {icon="fas fa-volume",value=1,name="1",},
            {icon="fas fa-volume",value=2,name="2",},
            {icon="fas fa-volume",value=3,name="3",},
            {icon="fas fa-volume",value=4,name="4",},
            {icon="fas fa-volume",value=5,name="5",},
            {icon="fas fa-volume",value=6,name="6",},
            {icon="fas fa-volume",value=7,name="7",},
        },
        ["Hitmarker"]={
            {icon="fas fa-xmark",value=0,name="Disable",},
            {image="Images/Hitmarker/1",value=1,name="1",},
            {image="Images/Hitmarker/2",value=2,name="2",},
            {image="Images/Hitmarker/3",value=3,name="3",},
            {image="Images/Hitmarker/4",value=4,name="4",},
        },
        ["CrosshairNormal"]={
            {image="Textures/Crosshairs/siteM16(0)",value=0,name="Default",},
            {image="Textures/Crosshairs/siteM16(1)",value=1,name="1",},{image="Textures/Crosshairs/siteM16(2)",value=2,name="2",},
            {image="Textures/Crosshairs/siteM16(3)",value=3,name="3",},{image="Textures/Crosshairs/siteM16(4)",value=4,name="4",},
            {image="Textures/Crosshairs/siteM16(5)",value=5,name="5",},{image="Textures/Crosshairs/siteM16(6)",value=6,name="6",},
            {image="Textures/Crosshairs/siteM16(7)",value=7,name="7",},{image="Textures/Crosshairs/siteM16(8)",value=8,name="8",},
            {image="Textures/Crosshairs/siteM16(9)",value=9,name="9",},{image="Textures/Crosshairs/siteM16(10)",value=10,name="10",},
            {image="Textures/Crosshairs/siteM16(11)",value=11,name="11",},{image="Textures/Crosshairs/siteM16(12)",value=12,name="12",},
            {image="Textures/Crosshairs/siteM16(13)",value=13,name="13",},{image="Textures/Crosshairs/siteM16(14)",value=14,name="14",},
            {image="Textures/Crosshairs/siteM16(15)",value=15,name="15",},{image="Textures/Crosshairs/siteM16(16)",value=16,name="16",},
            {image="Textures/Crosshairs/siteM16(17)",value=17,name="17",},{image="Textures/Crosshairs/siteM16(18)",value=18,name="18",},
            {image="Textures/Crosshairs/siteM16(19)",value=19,name="19",},{image="Textures/Crosshairs/siteM16(20)",value=20,name="20",},
            {image="Textures/Crosshairs/siteM16(21)",value=21,name="21",},{image="Textures/Crosshairs/siteM16(22)",value=22,name="22",},
            {image="Textures/Crosshairs/siteM16(24)",value=23,name="23",},{image="Textures/Crosshairs/siteM16(24)",value=24,name="24",},
            {image="Textures/Crosshairs/siteM16(25)",value=25,name="25",},{image="Textures/Crosshairs/siteM16(26)",value=26,name="26",},
            {image="Textures/Crosshairs/siteM16(27)",value=27,name="27",},{image="Textures/Crosshairs/siteM16(28)",value=28,name="28",},
            {image="Textures/Crosshairs/siteM16(29)",value=29,name="29",},{image="Textures/Crosshairs/siteM16(30)",value=30,name="30",},
            {image="Textures/Crosshairs/siteM16(31)",value=31,name="31",},{image="Textures/Crosshairs/siteM16(32)",value=32,name="32",},
            {image="Textures/Crosshairs/siteM16(33)",value=33,name="33",},{image="Textures/Crosshairs/siteM16(34)",value=34,name="34",},
            {image="Textures/Crosshairs/siteM16(35)",value=35,name="35",},{image="Textures/Crosshairs/siteM16(36)",value=36,name="36",},
            {image="Textures/Crosshairs/siteM16(37)",value=37,name="37",},{image="Textures/Crosshairs/siteM16(38)",value=38,name="38",},
            {image="Textures/Crosshairs/siteM16(39)",value=39,name="39",},{image="Textures/Crosshairs/siteM16(40)",value=40,name="40",},
            {image="Textures/Crosshairs/siteM16(41)",value=41,name="41",},{image="Textures/Crosshairs/siteM16(42)",value=42,name="42",},
            {image="Textures/Crosshairs/siteM16(43)",value=43,name="43",},{image="Textures/Crosshairs/siteM16(44)",value=44,name="44",},
            {image="Textures/Crosshairs/siteM16(45)",value=45,name="45",},{image="Textures/Crosshairs/siteM16(46)",value=46,name="46",},
            {image="Textures/Crosshairs/siteM16(47)",value=47,name="47",},{image="Textures/Crosshairs/siteM16(48)",value=48,name="48",},
            {image="Textures/Crosshairs/siteM16(49)",value=49,name="49",},{image="Textures/Crosshairs/siteM16(50)",value=50,name="50",},
            {image="Textures/Crosshairs/siteM16(51)",value=51,name="51",},{image="Textures/Crosshairs/siteM16(52)",value=52,name="52",},
        },
        ["CrosshairSniper"]={
            {image="Textures/Crosshairs/SNIPERcrosshair(0)",value=0,name="Default",},
            {image="Textures/Crosshairs/SNIPERcrosshair(1)",value=1,name="1",},{image="Textures/Crosshairs/SNIPERcrosshair(2)",value=2,name="2",},
            {image="Textures/Crosshairs/SNIPERcrosshair(3)",value=3,name="3",},{image="Textures/Crosshairs/SNIPERcrosshair(4)",value=4,name="4",},
            {image="Textures/Crosshairs/SNIPERcrosshair(5)",value=5,name="5",},{image="Textures/Crosshairs/SNIPERcrosshair(6)",value=6,name="6",},
            {image="Textures/Crosshairs/SNIPERcrosshair(7)",value=7,name="7",},{image="Textures/Crosshairs/SNIPERcrosshair(8)",value=8,name="8",},
            {image="Textures/Crosshairs/SNIPERcrosshair(9)",value=9,name="9",},{image="Textures/Crosshairs/SNIPERcrosshair(10)",value=10,name="10",},
            {image="Textures/Crosshairs/SNIPERcrosshair(11)",value=11,name="11",},{image="Textures/Crosshairs/SNIPERcrosshair(12)",value=12,name="12",},
            {image="Textures/Crosshairs/SNIPERcrosshair(13)",value=13,name="13",},{image="Textures/Crosshairs/SNIPERcrosshair(14)",value=14,name="14",},
            {image="Textures/Crosshairs/SNIPERcrosshair(15)",value=15,name="15",},{image="Textures/Crosshairs/SNIPERcrosshair(16)",value=16,name="16",},
            {image="Textures/Crosshairs/SNIPERcrosshair(17)",value=17,name="17",},{image="Textures/Crosshairs/SNIPERcrosshair(18)",value=18,name="18",},
            {image="Textures/Crosshairs/SNIPERcrosshair(19)",value=19,name="19",},{image="Textures/Crosshairs/SNIPERcrosshair(20)",value=20,name="20",},
            {image="Textures/Crosshairs/SNIPERcrosshair(21)",value=21,name="21",},
        },
        ["WindowsNotifications"]={
            {icon="fas fa-xmark",value=0,name="Disable",},
            {icon="da-duotone fa-solid fa-check",value=1,name="Enable",},
        },
        ["Effects"]={
            {icon="fas fa-xmark",value=0,name="Disable",type="Snow"},
            {icon="fas fa-cloud-snow",value=1,name="Enable",type="Snow"},

            {icon="fas fa-xmark",value=0,name="Disable",type="Bloodscreen"},
            {icon="fas fa-droplet",value=1,name="1",type="Bloodscreen"},
            {icon="fas fa-droplet",value=2,name="2",type="Bloodscreen"},
            {icon="fas fa-droplet",value=3,name="3",type="Bloodscreen"},
        },
        ["Shaders"]={
            {icon="fas fa-xmark",value=1,name="Disable",type="Paintjobs"},
            {icon="far fa-spray-can",value=0,name="Enable",type="Paintjobs"},

            {icon="fas fa-xmark",value=1,name="Disable",type="Lightjobs"},
            {icon="far fa-spray-can",value=0,name="Enable",type="Lightjobs"},

            {icon="fas fa-xmark",value=1,name="Disable",type="Windowtints"},
            {icon="far fa-spray-can",value=0,name="Enable",type="Windowtints"},
        },
    },
    Premium={
        ["Crates"]={
            {image="Images/Crates/WeaponSkins",value=1,name="WeaponSkins",price=50,},
            {image="Images/Crates/PedSkins",value=2,name="PedSkins",price=50,},
            {image="Images/Crates/Wheels",value=3,name="Wheels",price=25,},
        },

        TimeTillPedSkinExpires=604800,--7 days (only use days or the notifiy will bug)
    },
}